server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/arkana-db
    username: arkana
    password: arkana
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: redis
    port: 6379

  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org.springframework: INFO
    com.yourcompany: DEBUG
